name: Set Date Started on Issue Assign

on:
  issues:
    types: [assigned]

jobs:
  update-project-date-started:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Get ProjectV2Item ID for the Issue
        id: get_item_id
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          ITEM_ID=$(gh api graphql -f query='
          {
            node(id: "${{ env.ISSUE_ID }}") {
              ... on Issue {
                projectItems(first: 1) {
                  nodes {
                    id
                  }
                }
              }
            }
          }' | jq -r '.data.node.projectItems.nodes[0].id')

          if [[ -z "$ITEM_ID" || "$ITEM_ID" == "null" ]]; then
            echo "Error: Could not find ProjectV2Item ID for issue ${{ env.ISSUE_ID }}"
            exit 1
          fi
          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV

      - name: Update Project "Date Started" Field
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          PROJECT_ID: "PVT_kwHOBD1pUc4A0LJt"
          FIELD_ID: "PVTF_lAHOBD1pUc4A0LJtzgp2fA0"
        run: |
          gh api graphql -f query='
          mutation {
            updateProjectV2ItemFieldValue(
              input: {
                projectId: "${{ env.PROJECT_ID }}"
                itemId: "${{ env.ITEM_ID }}"
                fieldId: "${{ env.FIELD_ID }}"
                value: { text: "${{ env.date }}" }
              }
            ) {
              clientMutationId
            }
          }'
